import json
import os
from flask import Flask, request, send_file, jsonify
from flask_cors import CORS
import boto3
from tempfile import NamedTemporaryFile
import re

app = Flask(__name__)
CORS(app)

# Configure AWS clients
bedrock_client = boto3.client(
    service_name='bedrock-runtime',
    region_name='us-east-1',
)

polly_client = boto3.client('polly', region_name='us-east-1')

MODEL_ID = "anthropic.claude-3-5-sonnet-20240620-v1:0"
MODEL_ARN = f"arn:aws:bedrock:us-east-1::foundation-model/{MODEL_ID}"
knowledgeID = "EU3Z7J6SG6"
knowledgeType = "KNOWLEDGE_BASE"

def generate_text_with_bedrock(user_input):
    """
    Generate text using AWS Bedrock.
    """
    messages = [
        {
            "role": "user",
            "content": [
                          {
            "type": "text",
            "text":"Generate a paragraph in English based on Electromagnetism. The paragraph should be wrapped in single quotes. ''  and after generating the paragraph generate questions that are wrapped in ``` ```"
          }
            ]
        }
    ]

    try:
        # Prepare request body
        body = json.dumps({
            "messages": messages,
            "max_tokens": 1000,
            "temperature": 0.7,  # Adjust as needed
            "anthropic_version": "bedrock-2023-05-31"  # Replace with the correct version
        })

        # Make the API call
        response = bedrock_client.invoke_model(
            modelId=MODEL_ID,
            contentType='application/json',
            accept='application/json',
            body=body
        )

        # Access the response body
        streaming_body = response['body']
        response_body = json.loads(streaming_body.read().decode('utf-8')) 
        print(response_body)

        # Extract generated text
        generated_text = response_body['content'][0]['text']
        return generated_text
    except Exception as e:
        print(f"Error: {e}")
        return f"Error generating text: {str(e)}"


def synthesize_speech(text, voice_id='Joanna', output_format='mp3'):
    """
    Generate speech audio using AWS Polly.
    """
    try:
        response = polly_client.synthesize_speech(
            Text=text,
            VoiceId=voice_id,
            OutputFormat=output_format
        )
        audio_stream = response['AudioStream'].read()
        return audio_stream
    except Exception as e:
        return None, f"Error generating audio: {str(e)}"

@app.route('/generate', methods=['POST'])
def generate():
    """
    Generate text using Bedrock and convert it to speech using Polly.
    """
    data = request.get_json()
    user_input = data.get('user_input', '')
    template = data.get('template', 'You are a helpful assistant. Explain the following:\n\n{input}')

    # Generate text using Bedrock
    generated_text = generate_text_with_bedrock(user_input)
    if generated_text.startswith("Error"):
        return jsonify({"error": generated_text}), 500

    # Separate paragraph and questions
    paragraph = re.search(r"'(.*?)'", generated_text)
    questions = re.findall(r'```(.*?)```', generated_text, re.DOTALL)

    paragraph_text = paragraph.group(1) if paragraph else ""
    questions_text = "\n".join(questions)

    # Generate audio for the paragraph
    audio_data = synthesize_speech(text=paragraph_text, voice_id='Joanna')
    if not audio_data:
        return jsonify({"error": "Error generating audio"}), 500

    # Save audio to a temporary file
    temp_audio_file = NamedTemporaryFile(delete=False, suffix=".mp3")
    temp_audio_file.write(audio_data)
    temp_audio_path = temp_audio_file.name
    temp_audio_file.close()

    # Return the separated content and audio file path
    return jsonify({
        "paragraph_text": paragraph_text,
        "questions_text": questions_text,
        "audio_path": temp_audio_path
    })

@app.route('/get-audio', methods=['GET'])
def get_audio():
    """
    Retrieve audio file generated by Polly.
    """
    audio_path = request.args.get('path')
    if audio_path and os.path.exists(audio_path):
        return send_file(audio_path, mimetype='audio/mpeg')
    else:
        return jsonify({"error": "File not found"}), 404

if __name__ == '__main__':
    app.run(debug=True)
